### ISSUE TITLE
Kernel6.1.46 Cross compile error

### ISSUE THREAD

**Issue by coollhc77** [8devices/qcacld-2.0#21]
Hello.

Is it possible to cross compile with kernel 6.1.46 version?
I get the error: ././include/linux/compiler_types.h:113:10: fatal error: asm/compiler.h.

Please check, thank you.

**Comment by valinskas** [comment]
The latest linux kernel that 8devices has tried and seen it working on - Linux 5.10.x / 5.15.x
